name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations! This is your first issue. Thank you for helping to keep this application stable.'
        pr-message: 'Congratulations! This is your first awesome Pull request. Keep moving!'
